if(NOT DEFINED TARGET_DIR)
    message(FATAL_ERROR "EditorPostBuild.cmake: TARGET_DIR is required")
endif()

if(CONFIG STREQUAL "Release" OR CONFIG STREQUAL "RelWithDebInfo" OR CONFIG STREQUAL "MinSizeRel")
    set(HIMII_ENGINE_DIR "${TARGET_DIR}/HimiiEngine")
    file(MAKE_DIRECTORY "${HIMII_ENGINE_DIR}")

    if(EXISTS "${ENGINE_HPCK}")
        file(COPY_FILE "${ENGINE_HPCK}" "${HIMII_ENGINE_DIR}/engine.hpck" ONLY_IF_DIFFERENT)
    else()
        message(WARNING "EditorPostBuild: engine.hpck not found at ${ENGINE_HPCK}")
    endif()

    foreach(script_core_file ScriptCore.dll ScriptCore.runtimeconfig.json ScriptCore.xml)
        set(source_file "${SCRIPT_CORE_DIR}/${script_core_file}")
        if(EXISTS "${source_file}")
            file(COPY_FILE "${source_file}" "${HIMII_ENGINE_DIR}/${script_core_file}" ONLY_IF_DIFFERENT)
        endif()
    endforeach()

    set(script_core_pdb "${SCRIPT_CORE_DIR}/ScriptCore.pdb")
    if(EXISTS "${script_core_pdb}")
        file(COPY_FILE "${script_core_pdb}" "${HIMII_ENGINE_DIR}/ScriptCore.pdb" ONLY_IF_DIFFERENT)
    endif()

    set(default_layout_ini "${HIMII_EDITOR_DIR}/resources/default/editor_layout.ini")
    if(EXISTS "${default_layout_ini}")
        if(NOT EXISTS "${TARGET_DIR}/editor_layout.ini")
            file(COPY_FILE "${default_layout_ini}" "${TARGET_DIR}/editor_layout.ini")
        endif()
    endif()
else()
    file(MAKE_DIRECTORY "${TARGET_DIR}/assets")
    file(MAKE_DIRECTORY "${TARGET_DIR}/resources")

    file(COPY "${HIMII_EDITOR_DIR}/assets/." DESTINATION "${TARGET_DIR}/assets")
    file(COPY "${HIMII_EDITOR_DIR}/resources/." DESTINATION "${TARGET_DIR}/resources")

    foreach(script_core_file ScriptCore.dll ScriptCore.pdb ScriptCore.runtimeconfig.json ScriptCore.xml)
        set(source_file "${SCRIPT_CORE_DIR}/${script_core_file}")
        if(EXISTS "${source_file}")
            file(COPY_FILE "${source_file}" "${TARGET_DIR}/${script_core_file}" ONLY_IF_DIFFERENT)
        endif()
    endforeach()
endif()
